### ISSUE TITLE
telfhash library to pip

### ISSUE THREAD

**Issue by mlodic** [trendmicro/telfhash#3]
Could you upload the library to `pip`? In this way I can integrate it more easily in already existing projects.

Thank you in advance and great work with this!

**Comment by mlodic** [comment]
@merces @crhenr ?

**Comment by mlodic** [comment]
I guess I'll create a package with a fork of this :(

**Comment by merces** [comment]
Hi @mlodic! Sorry about the huge delay. I'm currently the only maintainer of Telfhash and honestly I wish I could invest more time on it. I have no experience with pip packaging. Do you think you can help us with a PR here?

**Comment by merces** [comment]
Update: I'm working on it.

**Comment by mlodic** [comment]
Yep it works correctly! We haven't integrated it in IntelOwl yet (we have an open issue) but yes it works.
