### ISSUE TITLE
telfhash grouping does not work with new tlsh format hashes

### ISSUE THREAD

**Issue by armijnhemel** [trendmicro/telfhash#4]
It appears that the grouping feature doesn't work with the new style TLSH hashes (the ones starting with `t`), because of the following check in `grouping.py`:

```
    #
    # TLSH hash is 70 characters long. if the telfhash is not 70
    # characters in length, exclude from the list
    #
    files_list = [x for x in list(telfhash_data.keys()) if telfhash_data[x]["telfhash"] is not None and len(telfhash_data[x]["telfhash"]) == 70]

```

This causes files_list to be empty and then eventually throws an error:

```
    files_list += distances[-1:][0][:2]
IndexError: list index out of range

```

The new hash used in TLSH (since 4.4.1) is 72 bytes long. There is a compatibility method called `oldhash()` that you might want to use, or you might want to drop support for TLSH < 4.4.1.

**Comment by armijnhemel** [comment]
In case you decide to drop support for TLSH < 4.4.1, then you want to change this in telfhash.py

```
    return tlsh.forcehash(encoded_symbol_string).lower()
```

because otherwise TLSH cannot diff the two hashes, as it expects the hashes to start with `T1` (uppercase), not `t1`.

**Comment by merces** [comment]
That's fixed now. Thanks for your report, @armijnhemel!
