### ISSUE TITLE
telfhash cannot process non-ascii symbol strings

### ISSUE THREAD

**Issue by armijnhemel** [trendmicro/telfhash#7]
There are ELF files with non-ascii symbol strings, which `telfhash` cannot process. An example can be downloaded from F-Droid:

https://f-droid.org/en/packages/io.github.x0b.rcx/

I downloaded version 1.12.2 which you can download directly from here: https://f-droid.org/repo/io.github.x0b.rcx_220.apk

After unzipping you can see that there are ELF binaries in the directory `lib/`. These contain symbols with non-ascii characters, which telfhash doesn't like. `readelf` shows this:

```
   110: 01b9a350     4 OBJECT  GLOBAL DEFAULT   23 github.com/rclone/rclone/backend/mailru/mrhash.New<C2>f
   111: 01b9b8ec     4 OBJECT  GLOBAL DEFAULT   23 runtime.markrootFreeGStacks<C2>f
```

but there are more symbols like that. `telfhash` gives the following error:

```
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 78115: ordinal not in range(128)
```

It seems that Golang allows Unicode characters in function names (for example, see https://groups.google.com/g/golang-nuts/c/MdYlJbW4SAo ) and these end up in the symbol names as well.

**Comment by merces** [comment]
Thanks for your bug report!
